import Head from "next/head";
import { connect } from "react-redux";
import {
  incrementCounter,
  decrementCounter,
} from "../redux/actions/conterActions";

function Home(props) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="font-bold text-5xl w-full">Nextjs + Tailwindcss template</div>
      <div>
        <h1>Counter : {props.counter}</h1>
        <button onClick={props.incrementCounter}>+ Count up</button>;
        <button onClick={props.decrementCounter}>+ Count down</button>
      </div>
    </div>
  );
}

// mapStateToProps
// รับฟังก์ชันจาก store มาใช้งาน
const mapStateToProps = (state) => ({
  counter: state.counter.value,
});

// mapDispatchToProps
// ส่งค่าไปยัง store เป็น object
const mapDispatchToProps = {
  incrementCounter: incrementCounter,
  decrementCounter: decrementCounter,
};

export default connect(mapStateToProps, mapDispatchToProps)(Home);
